### ISSUE TITLE
Svelte support?

### ISSUE THREAD

**Issue by FractalHQ** [frandiox/vitedge#10]
Hey!  Svelte support would be amazing.  Especially since Sveltekit is built around Vite 🙏.  Any plans for it?

**Comment by frandiox** [comment]
@FractalHQ Hi, thanks for your interest!

I'd like to support Svelte but I don't really know much about this framework so I'm afraid I might come up with an integration that doesn't feel natural for Svelte developers. Until I have time and energy to learn more about it, I'm welcome to contributions so I think the best I can do is give some pointers in case you or anybody else want to help with it:

The rendering happens in [`vite-ssr`](https://github.com/frandiox/vite-ssr) library so it must be implemented there. There's already support for [Vue](https://github.com/frandiox/vite-ssr/tree/master/src/vue) and [React](https://github.com/frandiox/vite-ssr/tree/master/src/react), so Svelte should follow the same guidelines (i.e. adding a `svelte` folder with `entry-client` and `entry-server`). Then, we also need to modify the [plugin](https://github.com/frandiox/vite-ssr/blob/master/src/plugin.js#L11) to detect Svelte.

There are two open questions that I don't know about:
- Routing in Svelte. Instead of implementing a new router, `vite-ssr` relies on each framework's router to make it feel more natural for developers. However, I see there are a bunch of routers for Svelte in the community and I'm not sure what's the best fit. Ideally, we would have some kind of  "before enter" route guard where one can fetch data and pass it as page props, like we do in Vue. Otherwise, it's possible to wrap the page components in "props provider" components like in the React integration (but this might have some caveats).
- Asynchronous rendering in the server: it should be possible to await data fetching or any other asynchronous call. [Vue](https://github.com/frandiox/vite-ssr/blob/f0a7e023cafa767c46d287a99623498381795529/src/vue/entry-server.js#L53) supports it out of the box whereas [React](https://github.com/frandiox/vite-ssr/blob/f0a7e023cafa767c46d287a99623498381795529/src/react/entry-server.js#L48) needs some extra help to make Suspense work in the server. I'm not sure if Svelte can support this easily.

After updating `vite-ssr`, integrating it in Vitedge should be very simple.

**Comment by FractalHQ** [comment]
Ah makes sense!

Svelte now has built-in support for routing, ssr components, and Vite via Sveltekit.  So it should be straightforward!

That being said, I think I'm going to wait for Svitekit to get out of Beta before I attempt this.

Thanks for pointing me in the right direction!  This should be all I need to take a stab at it once the Sveltekit API is frozen and merged into Svelte in v1 🙏

**Comment by frandiox** [comment]
@FractalHQ Hello! Is there any news in Svelte/SvelteKit related to this?

**Comment by FractalHQ** [comment]
Hey!  Yea, there's been a lot of progress:

- The official [router](https://kit.svelte.dev/docs#routing) and it's various [hooks](https://kit.svelte.dev/docs#hooks)
- The [Load](https://kit.svelte.dev/docs#loading) function that runs before a page or component is created, either on the client or the server for SSR.
- [Adapters](https://kit.svelte.dev/docs#adapters) allowing for backend agnostic code to run in various environments, including a [cloudflare-workers](https://kit.svelte.dev/docs#adapters) adapter.

**Comment by frandiox** [comment]
@FractalHQ Thanks! Looks like SvelteKit does the same things Vitedge does for other frameworks, so I'm not sure if there's any reason to support Svelte in Vitedge 🤔

**Comment by FractalHQ** [comment]
Hmm, yea I should probably close this for now 😅.  Thanks!!
