### ISSUE TITLE
API parameters

### ISSUE THREAD

**Issue by rohanbabuam** [frandiox/vitedge#28]
Hi, thank you for this amazing project. I read in the docs that API parameters are not currently supported out of the box and must be done manually. Is there an example of how to do it manually? If not would it be possible to provide an example or guidance on how I could do that please?

**Comment by frandiox** [comment]
@rohanbabuam Hi, thanks for your interest in the project!

Yeah, url parameters are not supported right now. It shouldn't be hard to implement but I just need time for it.

Alternatives are:
1. Use query-string with GET requests instead of params.
2. Use POST if possible and just send data in the body instead of URL params.
3. Since you have access to the entry point for the worker (`worker-site/index.js`, where you call Vitedge's `handleEvent`), you can always inspect the `event` object before passing it to Vitedge and handle the request yourself (check `event.request.url` to see if the route matches your custom endpoint). It won't be available during development, though.

I think I might be able to implement this during the weekend, so perhaps options 1-2 might be good enough for now until it is supported.

**Comment by rohanbabuam** [comment]
Brilliant!! Thanks for your support.

**Comment by frandiox** [comment]
Will be released soon 👍
