### ISSUE TITLE
Some sub modules does got missing after build ( on production )

### ISSUE THREAD

**Issue by calebeaires** [frandiox/vitedge#41]
after build vitedge does not handle modules that where importer by others. Here is the error I get when try to use vitedge with node (default example)

While building this error occurs

```bash
preferring built-in module 'querystring' over local alternative at '/Users/somedrive/Downloads/gn/node_modules/querystring/index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

```

```bash
 Cannot find package 'object-assign' imported from /Users/somedrive/Downloads/gn/dist/functions.js
code: 'ERR_MODULE_NOT_FOUND'
```

I am using a lib to connect to a database. When I move this same code to server/index.js (express) everything goes ok, but when I try to use into `functions/api` that error come out.

Here is how I call the lib

```js
import ClickHouse from '@apla/clickhouse';
const ch = new ClickHouse({ host: 'localhost', port: 8123, user: 'default', password: 'justpass' });
```

The missing module is already installed by the main module (Clickhouse lib). It supposes to not ask to install it on our vitedge app.

**Comment by frandiox** [comment]
@calebeaires Hi! Are you sure that package is installing the dependencies? I cannot see them here: https://github.com/apla/node-clickhouse/blob/master/package.json#L30

I think that package is using `require` (Common JS) to add polyfills conditionally at run time, which is not good for the static analysis that Rollup does. It should work if you install `object-assign` and `buffer-indexof-polyfill` manually. Otherwise, you can provide mockups when you call the plugin (using Rollup's Aliases):

```js
vitedge({
      functions: {
        build: {
          resolve: {
            alias: [
              {
                find: 'buffer-indexof-polyfill',
                replacement: path.resolve(process.cwd(), 'empty.js'),
              },
              {
                find: 'object-assign',
                replacement: path.resolve(process.cwd(), 'empty.js'),
              },
            ],
          },
        },
      },
    })
```

Where `empty.js` is a dummy file that contains `exports default {}`.

Hope that helps!

**Comment by calebeaires** [comment]
It worked. I was using vite-ssr but vitedge has a functioning (API + Props) system that makes it easy to create projects.
Hope this project got a far future away...!

 Thanks.
