### ISSUE TITLE
webpack is not working

### ISSUE THREAD

**Issue by domsen123** [frandiox/vitedge#52]
wondering why [Webpack](https://vitedge.js.org/usage.html#deploying-to-cloudflare-workers) isn't working.

wrangler.toml

```
name = "vitessedge"
type = "javascript"
account_id = "***"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = ""
watch_dir = "dist/worker"

[build.upload]
format = "service-worker"
```

webpack.config.js

```
module.exports = {
  ...require('vitedge/webpack.cjs')(options),
}
```

package.json:

`main` in `package.json` is set to `dist/worker/script.js` and `type: module` is removed

Error:
```👀  Entry module not found: Error: Can't resolve './index' in '/home/dmarx/projects/project-docs'
resolve './index' in '/home/dmarx/projects/project-docs'
  using description file: /home/dmarx/projects/project-docs/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/dmarx/projects/project-docs/package.json (relative path: ./index)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/dmarx/projects/project-docs/index doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/dmarx/projects/project-docs/index.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /home/dmarx/projects/project-docs/index.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/dmarx/projects/project-docs/index.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/dmarx/projects/project-docs/index.json doesn't exist
      as directory
        /home/dmarx/projects/project-docs/index doesn't exist
Error: webpack returned an error. Try configuring `entry` in your webpack config relative to the current working directory, or setting `context = __dirname` in your webpack config.
```

**Comment by frandiox** [comment]
You are using the config for ESBuild, not for Webpack. In the docs you can check the actual wrangler.toml.
The `main` in your package.json should also point to the **entry** file (where you use `addEventListener`), not to the output script.

There's an example here: https://github.com/frandiox/vitedge/tree/master/examples/worker-site

**Comment by domsen123** [comment]
thank you @frandiox - it works

but as soon as I add FaunaDB to the API its not working anymore 😅

idk - maybe some module/commonjs thing...

**Comment by frandiox** [comment]
@domsen123 Vite has known issues when bundling certain modules such as `aws-sdk`. Perhaps Fauna is also problematic in Vite.

Can you try `vitedge@0.14.0` and tell me if that works? That version was using Rollup instead of Vite for bundling backend stuff and works with `aws-sdk` at least. I'm planning on switching to ESBuild for the next version, which should fix this kind of issues.

**Comment by frandiox** [comment]
@domsen123 I'm closing this issue since the original problem was related to Webpack and seems that it's solved.

About Fauna, I've seen you reported something on their repo and they fixed it. With that fix it builds although I'm not sure if it will work. Fauna package is very coupled with commonjs and Node, so perhaps something fails when Vite tries to bundle it for worker environment.
If that's the case, try to mark Fauna as an external dependency in Vite and let Webpack do the bundling work like this:

```js
// vite.config.js plugins

vitedge({
    functions: {
      build: {
        rollupOptions: {
          external: ['faunadb']
        }
      }
    }
  })
```

This should work at least in `vitedge@0.16.0`.
